language: node_js
cache:
  directories:
    - "node_modules"
install:
  - git clone https://github.com/kylehovey/nest-safely
  - cd nest-safely
  - yarn global add eslint
  - yarn install
script:
  - yarn test
  - yarn lint
